In [2]:
import pandas as pd 
print(pd.__version__)

2.2.2

In [5]:
emp = {
    "id" : [1,2,3,4,5,6,7],
    "name" : ["yash","manav","arpit","poojan","juzer","ishan","shubham"],
    "dept" : ["it","comp","comp","it","comp","it","ec"],
    "salary" : [500000,200000,400000,600000,100000,250000,450000]
}
df = pd.DataFrame(emp)
df

   id     name  dept  salary
0   1     yash    it  500000
1   2    manav  comp  200000
2   3    arpit  comp  400000
3   4   poojan    it  600000
4   5    juzer  comp  100000
5   6    ishan    it  250000
6   7  shubham    ec  450000

In [12]:
df['dept'].value_counts()

dept
it      3
comp    3
ec      1
Name: count, dtype: int64

In [13]:
student = {
    'first' : ['yash','manav','poojan','arpit','juzer','ishan','shubham','parth','naughty','kush'],
    'last' : ['patel','shah','patel','shah','doshi','doshi','patel','patel','patel','patel'],
    'email' : ['yash@gmail.com','manav@gmail.com','poojan@gmail.com','arpit@gmail.com','juzer@gmail.com','ishan@gmail.com','shubham@gmail.com','parth@gmail.com','kush@gmail.com','abhishek@gmail.com'],
    'college' : ['changa','svit','changa','iti','svit','nirma','svit','changa','svit','changa'],
    'per' : [90,80,70,20,46,82,67,94,58,91],
    'grade' : ['aa','bb','cc','aa','aa','bb','dd','aa','cc','aa']
}
df = pd.DataFrame(student)
df

     first   last               email college  per grade
0     yash  patel      yash@gmail.com  changa   90    aa
1    manav   shah     manav@gmail.com    svit   80    bb
2   poojan  patel    poojan@gmail.com  changa   70    cc
3    arpit   shah     arpit@gmail.com     iti   20    aa
4    juzer  doshi     juzer@gmail.com    svit   46    aa
5    ishan  doshi     ishan@gmail.com   nirma   82    bb
6  shubham  patel   shubham@gmail.com    svit   67    dd
7    parth  patel     parth@gmail.com  changa   94    aa
8  naughty  patel      kush@gmail.com    svit   58    cc
9     kush  patel  abhishek@gmail.com  changa   91    aa

In [14]:
df['per'].max()

94

In [16]:
df.shape

(10, 6)