In [1]:
import pandas as pd
df = pd.read_csv("Dataset\\weather_data1.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [10]:
import numpy as np
new_df = df.replace([-99999,"0"df = pd. DataFrame ({
'score' : ['exceptional', 'average','good ,l' exceptional'],
'student' : ['nano', 'maya', 'prem', 'jay', 'jainam' ]
})],np.nan)
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0    NaN

In [12]:
df = pd. DataFrame ({
'score' : ['exceptional','average','good','exceptional','good'],
'student' : ['nano', 'maya', 'prem', 'jay', 'jainam' ]
})
df

         score student
0  exceptional    nano
1      average    maya
2         good    prem
3  exceptional     jay
4         good  jainam

In [13]:
df.replace(['poor','average','good','exceptional'],[1,2,3,4])

C:\Users\Jaina\AppData\Local\Temp\ipykernel_36028\2662941392.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(['poor','average','good','exceptional'],[1,2,3,4])

   score student
0      4    nano
1      2    maya
2      3    prem
3      4     jay
4      3  jainam